version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: DevPilot.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DevPilotDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - Jwt__Key=dev_secret_key_12345
    ports:
      - "5000:80"
    depends_on:
      sqlserver:
        condition: service_healthy
  frontend:
    build:
      context: ./webapp
    ports:
      - "3000:80"
    depends_on:
      - api
    volumes:
      - ./webapp:/app 